[package]
name = "tinysol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-sitter = '0.3.4'
ethnum = "1.3.2"
keccak-hash = "0.10.0"

[build-dependencies]
rust-sitter-tool = "0.3.4"
